
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_fully_connected_jax.ipynb

from exp.nb_01 import *

def get_data():
    x_train, y_train, x_valid, y_valid  = datasets.mnist()
    return map(jax.device_put, (x_train, y_train, x_valid, y_valid))

def normalize(x, m, s): return (x-m)/s

def test_near_zero(a,tol=1e-3): assert np.abs(a)<tol, f"Near zero: {a}"

def mse(output, targ): return np.mean(np.dot((output.squeeze(-1) - targ), (output.squeeze(-1) - targ)))